# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwordu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from re import sub
import time
from random import randint
w = 'w'
r = 'r'
wplus = 'w+'
def open_file(first,seconde):
    global a ,v 
    a = open('input.txt',first)
    v = open('output.txt',seconde)
def close_file():
    a.close()
    v.close()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 162)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.Exit.setObjectName("Exit")
        self.qlabel = QtWidgets.QLabel(self.centralwidget)
        self.qlabel.setGeometry(20,40,181,20)
        self.qlabel.setObjectName("qlabel1")
        self.OK = QtWidgets.QPushButton(self.centralwidget)
        self.OK.setGeometry(QtCore.QRect(120, 90, 75, 23))
        self.OK.setObjectName("OK")
        self.First = QtWidgets.QLineEdit(self.centralwidget)
        self.First.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.First.setObjectName("First")
        self.Seconde = QtWidgets.QLineEdit(self.centralwidget)
        self.Seconde.setGeometry(QtCore.QRect(130, 10, 113, 20))
        self.Seconde.setObjectName("Seconde")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 261, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Exit.clicked.connect(MainWindow.close)
        self.OK.clicked.connect(self.getdata)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def getdata(self):        
        firsT = self.First.text()
        secondE = self.Seconde.text()
        try:
            open_file(r,w)
        except FileNotFoundError:
            self.qlabel.setText('Excuse me File not founde please make that ')
        try:
            for word in a:
                self.qlabel.setText('workiinnnnggg')
                reader = a.readline()
                v.write(sub(firsT,secondE,word))
                v.write(sub(firsT,secondE,reader))
       
            close_file()    
            open_file(w,r)
            for cp in v :
                readercp = v.readline()
                a.write(cp)
                a.write(readercp)
            close_file()
            open_file(r,wplus)
            for delete in a :
                reader = v.readline()
                v.write(sub(r'.*','',delete))
                v.write(sub(r'.*','',reader))
            close_file()
            self.qlabel.setText('The end  ')
        except NameError:
            self.qlabel.setText('file not found')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
        self.OK.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
